CREATE TYPE "role" AS ENUM ('user', 'admin');
CREATE TYPE "incidentType" AS ENUM ('harassment', 'assault', 'stalking', 'theft', 'unsafe_area', 'other');
CREATE TYPE "severity" AS ENUM ('low', 'medium', 'high', 'critical');
CREATE TYPE "status" AS ENUM ('pending', 'verified', 'resolved', 'dismissed');

CREATE TABLE "users" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	"openId" varchar(64) NOT NULL,
	"name" text,
	"email" varchar(320),
	"loginMethod" varchar(64),
	"role" "role" DEFAULT 'user' NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"lastSignedIn" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "users_openId_unique" UNIQUE("openId")
);

CREATE TABLE "incidents" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	"latitude" numeric(10, 8) NOT NULL,
	"longitude" numeric(11, 8) NOT NULL,
	"incidentType" "incidentType" NOT NULL,
	"severity" "severity" NOT NULL,
	"description" text NOT NULL,
	"mediaUrls" json,
	"reportedAt" timestamp NOT NULL,
	"submittedAt" timestamp DEFAULT now() NOT NULL,
	"ipHash" varchar(64) NOT NULL,
	"status" "status" DEFAULT 'pending' NOT NULL,
	"adminNotes" text,
	"llmClassification" json,
	"trackingPin" varchar(10),
	"reporterAlias" text
);

CREATE TABLE "alertSubscriptions" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	"email" varchar(255) NOT NULL,
	"latitude" numeric(10, 8) NOT NULL,
	"longitude" numeric(10, 8) NOT NULL,
	"radiusKm" numeric(5, 2) DEFAULT '5.00' NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL
);

CREATE TABLE "media_attachments" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	"incidentId" integer NOT NULL,
	"s3Key" varchar(255) NOT NULL,
	"s3Url" varchar(512) NOT NULL,
	"mimeType" varchar(50) NOT NULL,
	"fileSize" integer NOT NULL,
	"uploadedAt" timestamp DEFAULT now() NOT NULL
);

CREATE TABLE "rate_limit_log" (
	"id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
	"ipHash" varchar(64) NOT NULL,
	"attemptedAt" timestamp DEFAULT now() NOT NULL,
	"endpoint" varchar(100) NOT NULL
);
